#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDD_ABOUT                               102
#define IDD_DEBUGGER                            104
#define IDR_WAVE1                               105
#define IDM_OPEN                                40000
#define IDC_V1                                  40001
#define IDM_CLOSE                               40001
#define IDC_CLOSE                               40002
#define IDM_EXIT                                40002
#define IDM_PAUSE                               40003
#define IDM_RESET                               40004
#define IDC_STEP                                40005
#define IDM_250Hz                               40005
#define IDC_V0                                  40006
#define IDM_500Hz                               40006
#define IDC_V2                                  40007
#define IDM_750Hz                               40007
#define IDC_V3                                  40008
#define IDM_1000Hz                              40008
#define IDC_V4                                  40009
#define IDM_PAUSE_WHEN_INACTIVE                 40009
#define IDC_V5                                  40010
#define IDM_LOW_CPU_MODE                        40010
#define IDC_V6                                  40011
#define IDM_DETECT_GAME_OVER                    40011
#define IDC_V7                                  40012
#define IDM_DETECT_COLLISION                    40012
#define IDC_V8                                  40013
#define IDM_ENABLE_HORIZONTAL_WRAP              40013
#define IDC_V9                                  40014
#define IDM_ENABLE_VERTICAL_WRAP                40014
#define IDC_VA                                  40015
#define IDM_DEBUGGER                            40015
#define IDC_VB                                  40016
#define IDM_ABOUT                               40016
#define IDC_VC                                  40017
#define IDM_SAVE_STATE                          40017
#define IDC_VD                                  40018
#define IDM_LOAD_STATE                          40018
#define IDC_VE                                  40019
#define IDM_X1                                  40019
#define IDC_VF                                  40020
#define IDM_X2                                  40020
#define IDC_PC                                  40021
#define IDM_X3                                  40021
#define IDC_OPCODE                              40022
#define IDM_X4                                  40022
#define IDC_I                                   40023
#define IDM_COLOR_DEFAULT                       40023
#define IDC_SP                                  40024
#define IDM_COLOR_INVERT                        40024
#define IDC_DT                                  40025
#define IDM_COLOR_RANDOM                        40025
#define IDC_ST                                  40026
#define IDM_CUSTOM                              40026
#define IDC_STACK                               40027
#define IDM_SOUND_ON                            40027
#define IDC_DISASSEMBLER                        40028
#define IDM_TURBO                               40028
#define IDC_MAIN_STATUS                         40029
